variants:
  default: {}
  descriptive:
    risk_factors_bias: "SYSTEMIC BIAS"
    harms_discrimination: "DISCRIMINATORY HARM"
    risk_factors_privacy: "DATA PRIVACY"
    harms_violation_of_civil_or_human_rights_including_privacy: "CIVIL RIGHTS"
  concise:
    risk_factors_bias: "BIAS"
    harms_discrimination: "HARM"
    risk_factors_privacy: "PRIVACY"
    harms_violation_of_civil_or_human_rights_including_privacy: "RIGHTS"
