"""Score audit reports against human gold briefs."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
from typing import Any

import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from policy_interp.audit_evidence_suite import score_audit_report, summarize_scores  # noqa: E402
from policy_interp.io import read_jsonl, write_jsonl  # noqa: E402
from policy_interp.utils import ensure_dir  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--reports",
        type=Path,
        default=ROOT / "artifacts" / "audit_evidence_eval" / "reports" / "audit_reports_dry_run.jsonl",
        help="Report JSONL generated by scripts/run_local_audit_reports.py.",
    )
    parser.add_argument(
        "--gold",
        type=Path,
        default=ROOT / "artifacts" / "audit_evidence_eval" / "gold" / "gold_briefs_template.jsonl",
        help="Human reviewed gold brief JSONL.",
    )
    parser.add_argument(
        "--packages",
        type=Path,
        default=ROOT / "artifacts" / "audit_evidence_eval" / "packages",
        help="Package JSONL file or directory.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "artifacts" / "audit_evidence_eval" / "scores" / "audit_report_scores.jsonl",
        help="Output score JSONL.",
    )
    parser.add_argument(
        "--summary",
        type=Path,
        default=ROOT / "artifacts" / "audit_evidence_eval" / "scores" / "audit_report_score_summary.csv",
        help="Output condition summary CSV.",
    )
    return parser.parse_args()


def load_packages(path: Path) -> dict[tuple[str, str], dict[str, Any]]:
    files = [path] if path.is_file() else sorted(path.glob("C*.jsonl"))
    index: dict[tuple[str, str], dict[str, Any]] = {}
    for file_path in files:
        for package in read_jsonl(file_path):
            key = (str(package.get("case_id")), str(package.get("condition_id")))
            index[key] = package
    return index


def main() -> None:
    args = parse_args()
    reports = read_jsonl(args.reports)
    gold_index = {str(record.get("case_id")): record for record in read_jsonl(args.gold)}
    package_index = load_packages(args.packages)

    scores: list[dict[str, Any]] = []
    for report in reports:
        case_id = str(report.get("case_id"))
        condition_id = str(report.get("condition_id"))
        gold = gold_index.get(case_id, {})
        package = package_index.get((case_id, condition_id), {"case_id": case_id, "condition_id": condition_id})
        scores.append(score_audit_report(report, gold, package))

    write_jsonl(scores, args.output)
    summary = summarize_scores(scores)
    ensure_dir(args.summary.parent)
    summary.to_csv(args.summary, index=False)
    status_counts = pd.Series([score.get("score_status") for score in scores]).value_counts().to_dict()
    print(f"Wrote {len(scores)} score records to {args.output}")
    print(f"Wrote summary to {args.summary}")
    print(f"Score status counts: {status_counts}")


if __name__ == "__main__":
    main()
